### ISSUE TITLE
Accesso Negato

### ISSUE THREAD

**Issue by YessaMinecraftMod** [Lampadina17/MorpheusLauncher#1]
Ciao Lampadina_17,
Nella console, si vede che Morpheus non riesce ad accedere ad alcuni assets di Minecraft, come devi fare? Alcune volte appare Unknown Source, c'è qualche cosa che non ho fatto?
![170594048388826384773896804566](https://github.com/Lampadina17/MorpheusLauncher/assets/142932802/18b951cb-cef7-48b2-882c-3de4307fd53a)
![17059405060733593074630876030417](https://github.com/Lampadina17/MorpheusLauncher/assets/142932802/abba6544-ce0e-47d3-889e-757d22f0bf42)

**Comment by Lampadina17** [comment]
Just delete .minecraft/assets folder, launcher will re-download assets automatically after next game launch
